jobs:
  include:
    - stage: test
      sudo: false
      language: javascript
      install: npm install
      script: npm run test:unit:js && npm run test:smoke:typescript
    - stage: build android
      language: android
      sudo: false
      android:
        components:
         - tools
         - platform-tools
         - build-tools-26.0.2
         - android-26
      env:
        - ANDROID_TARGET=android-26 ANDROID_ABI=armeabi-v7a
        - ADB-INSTALL_TIMEOUT=5
      install:
        - echo y | android update sdk -u -a -t android-23 
        - curl -sL https://deb.nodesource.com/setup_8.x | sudo -E bash -
        - sudo apt-get install -y nodejs
      script:
        - cd examples/plain
        - npm install
        - react-native link
        - cd android
        - ./gradlew assembleRelease
    - stage: build cocoa
      language: objective-c
      osx-image: xcode7.3
      env: SDK=macosx10.11 BUILD_OSX=1
      xcode_project: ./cocoa/BugsnagReactNative.xcodeproj
      xcode_scheme: BugsnagReactNative
      install:
        - curl -sL https://deb.nodesource.com/setup_8.x | sudo -E bash -
        - sudo apt-get install -y nodejs
      script:
        - cd examples/plain
        - npm install
        - react-native link
        - cd ios
        - xcodebuild -project BugsnagReactNativeExample.xcodeproj -scheme BugsnagReactNativeExample build CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO