jobs:
  include:
    - stage: test
      sudo: false
      language: javascript
      install: npm install
      script: npm run test:unit:js && npm run test:smoke:typescript
    - stage: build_android
      language: android
      android:
        components:
         - tools
         - platform-tools
         - build-tools-26.0.2
         - android-16
         - android-21
         - android-26
      env:
        - ANDROID_TARGET=android-21 ANDROID_ABI=armeabi-v7a
        - ADB-INSTALL_TIMEOUT=5
      script: ./android/gradlew assembleRelease
    - stage: build_cocoa
      language: objective-c
      osx-image: xcode7.3
      env: SDK=macosx10.11 BUILD_OSX=1
      xcode_project: ./cocoa/BugsnagReactNative.xcodeproj